# SPDX-FileCopyrightText: 2024-present Richard Dahl <richard@dahl.us>
#
# SPDX-License-Identifier: MIT
site_name: NotORM (Uno)
site_description: A comprehensive application framework for building data-driven applications with PostgreSQL and FastAPI
theme:
   name: material
   palette:
     primary: blue
     accent: indigo
   features:
     - navigation.tabs
     - navigation.sections
     - toc.integrate
     - search.suggest
     - search.highlight
plugins:
   - search
   - mkdocstrings
nav:
   - Home: index.md
   - Getting Started: getting_started.md
   - Architecture:
      - Overview: architecture/overview.md
      - Domain-Driven Design: architecture/domain_driven_design.md
      - Async-First Architecture: architecture/async_architecture.md
      - Async Implementation: architecture/async_implementation.md
   - Data Layer:
      - Overview: database/overview.md
      - Database Engine: database/engine.md
      - UnoDB: database/unodb.md
      - Testing: testing.md
   - Models Layer:
      - Overview: models/overview.md
      - UnoModel: models/model.md
   - Business Logic Layer:
      - Overview: business_logic/overview.md
      - UnoObj: business_logic/unoobj.md
      - Registry: business_logic/registry.md
      - Schema Management: business_logic/schema.md
   - API Layer:
      - Overview: api/overview.md
      - Endpoint: api/endpoint.md
      - Endpoint Factory: api/endpoint-factory.md
      - Filter Manager: queries/filter_manager.md
      - Schemas: api/schemas.md
   - Vector Search:
      - Overview: vector_search/overview.md
      - pgvector Integration: vector_search/pgvector_integration.md
      - Docker Setup: vector_search/docker_setup.md
      - API Usage: vector_search/api_usage.md
      - Dependency Injection: vector_search/dependency_injection.md
      - Hybrid Search: vector_search/hybrid_search.md
      - RAG Implementation: vector_search/rag.md
      - Event-Driven Architecture: vector_search/events.md
   - SQL Generation:
      - Overview: sql_generation/overview.md
      - Emitters: sql_generation/emitters.md
      - Statement: sql_generation/statement.md
      - Registry: sql_generation/registry.md
   - Type Safety:
      - Overview: type_safety/overview.md
      - Implementation: type_safety/implementation.md
      - Migration: type_safety/migration.md
   - Dependency Injection:
      - Overview: dependency_injection/overview.md
      - Migration: dependency_injection/migration.md
      - Examples: dependency_injection/examples.md
   - Protocol System:
      - Overview: protocols/overview.md
      - Protocol Validation: protocol_validation.md
      - Database Protocols: protocols/database_protocols.md
      - Generic Type Constraints: protocols/generic_type_constraints.md
   - Async Utilities:
      - Overview: async/overview.md
      - Task Management: async/task_management.md
      - Concurrency Primitives: async/concurrency.md
      - Context Management: async/context.md
      - Integration: async/integration.md
      - Application Lifecycle: async/lifecycle.md
   - Modernization:
      - Overview: modernization/overview.md
      - Key Features: modernization/key_features.md
      - Migration Guide: modernization/migration.md
   - Security:
      - Authorization: authorization/overview.md
   - Command Reference: commands.md
   - FAQ: faq.md
   - License: license.md
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - toc:
      permalink: true