# SPDX-FileCopyrightText: 2024-present Richard Dahl <richard@dahl.us>
#
# SPDX-License-Identifier: MIT
site_name: Uno Framework
site_description: A modern Python framework that integrates SQLAlchemy, Pydantic, and FastAPI with PostgreSQL 16.
repo_url: https://github.com/username/uno
repo_name: username/uno
strict: true
theme:
  name: material
  palette:
    primary: blue
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
  icon:
    repo: fontawesome/brands/github
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
  - git-revision-date-localized
site_url: https://example.com/
nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Tutorials:
      - Overview: tutorial/index.md
      - Migrating from SQLAlchemy: tutorial/migrating_from_sqlalchemy.md
      - Migrating from Django: tutorial/migrating_from_django.md
  - Architecture:
      - Overview: architecture/overview.md
      - Domain-Driven Design: architecture/domain_driven_design.md
      - Async-First Architecture: architecture/async_architecture.md
      - Event-Driven Architecture: architecture/event_driven_architecture.md
      - CQRS: architecture/cqrs.md
      - Bounded Contexts: architecture/bounded_contexts.md
      - Dependency Injection: architecture/dependency_injection.md
      - New Architecture: architecture/new_architecture.md
  - Core:
      - Overview: core/overview.md
      - Events:
          - Overview: core/events/index.md
          - Event Bus: core/events/bus.md
          - Event Store: core/events/store.md
          - Postgres Implementation: core/events/postgres.md
          - Subscription Management: core/events/subscription_management.md
      - Unit of Work:
          - Overview: core/uow/index.md
          - Base Implementation: core/uow/base.md
          - Distributed UoW: core/uow/distributed.md
          - Context Management: core/uow/context.md
      - Error Handling:
          - Overview: core/errors/overview.md
          - Result Pattern: core/errors/result.md
          - Error Catalog: core/errors/catalog.md
          - Logging Integration: core/errors/logging.md
      - Monitoring:
          - Overview: core/monitoring/overview.md
          - Health Checks: core/monitoring/health.md
          - Metrics: core/monitoring/metrics.md
          - Tracing: core/monitoring/tracing.md
          - Dashboard: core/monitoring/dashboard.md
      - Dependency Injection: core/dependency_injection.md
      - Validation: core/validation.md
      - Protocol Testing: core/protocol_testing.md
  - Domain:
      - Guide: domain/guide.md
      - Entity Framework: domain/entity_framework.md
      - Repository Pattern: domain/repository_pattern.md
      - Service Pattern: domain/service_pattern.md
      - Specification Pattern: domain/specification_pattern.md
      - Value Objects: domain/value_objects.md
      - Aggregates: domain/aggregates.md
      - Domain Events: domain/domain_events.md
  - API:
      - Overview: api/overview.md
      - Endpoint Framework:
          - Overview: api/endpoint/overview.md
          - Unified Endpoints: api/endpoint/unified_endpoint_framework.md
          - CQRS Pattern: api/endpoint/cqrs_pattern.md
          - Authentication: api/endpoint/authentication.md
          - Filtering: api/endpoint/filtering.md
          - OpenAPI: api/endpoint/openapi.md
      - DTOs: api/dto.md
  - Database:
      - Overview: database/overview.md
      - Connections: database/connections.md
      - Transactions: database/transactions.md
      - Query Optimization: database/query_optimization.md
      - PostgreSQL Features: database/postgresql_features.md
      - Apache AGE Integration: database/apache_age.md
  - Vector Search:
      - Overview: vector_search/overview.md
      - pgvector Integration: vector_search/pgvector.md
      - Hybrid Search: vector_search/hybrid_search.md
      - RAG Implementation: vector_search/rag.md
  - Infrastructure:
      - Database:
          - Overview: infrastructure/database/overview.md
          - Engines: infrastructure/database/engines.md
          - Session Management: infrastructure/database/sessions.md
          - Connection Pooling: infrastructure/database/connection_pooling.md
      - Messaging: infrastructure/messaging.md
      - Security:
          - Overview: infrastructure/security/overview.md
          - Authentication: infrastructure/security/authentication.md
          - Authorization: infrastructure/security/authorization.md
          - Encryption: infrastructure/security/encryption.md
      - Caching: infrastructure/caching.md
  - Application:
      - DTO Management: application/dto.md
      - Queries:
          - Overview: application/queries/overview.md
          - Filter Management: application/queries/filter_manager.md
          - Batch Operations: application/queries/batch_operations.md
          - Optimization: application/queries/optimization.md
      - Workflows:
          - Overview: application/workflows/overview.md
          - Engine: application/workflows/engine.md
          - Integration: application/workflows/integration.md
      - Jobs:
          - Overview: application/jobs/overview.md
          - Scheduler: application/jobs/scheduler.md
          - Workers: application/jobs/workers.md
          - Storage: application/jobs/storage.md
  - Features:
      - Attributes: features/attributes.md
      - Values: features/values.md
      - Reports: features/reports.md
      - Meta: features/meta.md
  - Developer Tools:
      - Overview: developer_tools/overview.md
      - CLI Commands: developer_tools/cli.md
      - Visual Modeler: developer_tools/modeler.md
      - Code Generation: developer_tools/code_generation.md
      - Documentation: developer_tools/documentation.md
      - Testing: developer_tools/testing.md
      - Profiling: developer_tools/profiling.md
  - Deployment:
      - Docker: deployment/docker.md
      - CI/CD: deployment/ci_cd.md
      - Production: deployment/production.md
      - Monitoring: deployment/monitoring.md
  - Reference:
      - Command Reference: reference/commands.md
      - API Reference: reference/api.md
      - Configuration Options: reference/configuration.md
      - Glossary: reference/glossary.md
  - Project:
      - Roadmap: project/roadmap.md
      - Contributing: project/contributing.md
      - FAQ: project/faq.md
      - License: project/license.md
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - attr_list
  - toc:
      permalink: true