# SPDX-FileCopyrightText: 2024-present Richard Dahl <richard@dahl.us>
#
# SPDX-License-Identifier: MIT

from uno.api.schemas import (
    InsertSchemaDef,
    DeleteSchemaDef,
    ImportSchemaDef,
    ListSchemaDef,
    SelectSchemaDef,
    UpdateSchemaDef,
)

tenant_schema_defs = [
    ListSchemaDef(
        include_fields=[
            "id",
            "name",
            "is_active",
        ],
    ),
    InsertSchemaDef(
        exclude_fields=[
            "id",
            "created_at",
            "created_by_id",
            "modified_at",
            "modified_by_id",
            "deleted_at",
            "deleted_by_id",
        ],
    ),
    SelectSchemaDef(),
    UpdateSchemaDef(
        exclude_fields=[
            "id",
            "created_at",
            "modified_at",
            "modified_by_id",
            "deleted_at",
            "deleted_by_id",
        ],
    ),
    DeleteSchemaDef(),
    ImportSchemaDef(),
]

user_schema_defs = [
    ListSchemaDef(
        include_fields=[
            "id",
            "handle",
            "is_active",
        ],
    ),
    InsertSchemaDef(
        exclude_fields=[
            "id",
            "created_at",
            "created_by_id",
            "modified_at",
            "modified_by_id",
            "deleted_at",
            "deleted_by_id",
            "is_active",
            "is_deleted",
        ],
    ),
    SelectSchemaDef(),
    UpdateSchemaDef(
        exclude_fields=[
            "id",
            "is_superuser",
            "tenant_id",
            "created_at",
            "created_by_id",
            "modified_at",
            "modified_by_id",
            "deleted_at",
            "deleted_by_id",
        ],
    ),
    DeleteSchemaDef(),
    ImportSchemaDef(),
]

group_schema_defs = [
    InsertSchemaDef(
        exclude_fields=[
            "id",
            "created_at",
            "created_by_id",
            "modified_at",
            "modified_by_id",
            "deleted_at",
            "deleted_by_id",
        ],
    ),
    ListSchemaDef(
        include_fields=[
            "id",
            "name",
            "is_active",
        ],
    ),
    SelectSchemaDef(),
    UpdateSchemaDef(
        exclude_fields=[
            "id",
            "created_at",
            "modified_at",
            "modified_by_id",
            "deleted_at",
            "deleted_by_id",
            "created_by",
            "modified_by",
            "deleted_by",
        ],
    ),
    DeleteSchemaDef(),
    ImportSchemaDef(),
]

role_schema_defs = [
    InsertSchemaDef(
        exclude_fields=[
            "id",
            "created_at",
            "created_by_id",
            "modified_at",
            "modified_by_id",
            "deleted_at",
            "deleted_by_id",
            "created_by",
            "modified_by",
            "deleted_by",
        ],
    ),
    ListSchemaDef(
        include_fields=[
            "id",
            "name",
            "is_active",
        ],
    ),
    SelectSchemaDef(),
    UpdateSchemaDef(
        exclude_fields=[
            "id",
            "created_at",
            "modified_at",
            "modified_by_id",
            "deleted_at",
            "deleted_by_id",
            "created_by",
            "modified_by",
            "deleted_by",
        ],
    ),
    DeleteSchemaDef(),
    ImportSchemaDef(),
]
