services:
  db:
    container_name: "pg16_uno"
    image: pg16_uno
    restart: always
    environment:
      POSTGRES_PASSWORDE: "postgreSQLR0ck%"
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres-data:/var/lib/postgresql/data:z
    ports:
      - "5432:5432"
volumes:
  postgres-data:
