services:
  db:
    container_name: "pg16_uno"
    image: "uno_pg:16-alpine"
    restart: always
    environment:
      POSTGRES_PASSWORDE: "postgreSQLR0ck%"
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres-data:/var/lib/postgresql/data:z
    ports:
      - "5432:5432"
    command: postgres -c shared_preload_libraries='/usr/local/lib/postgresql/plugins/age.so'
volumes:
  postgres-data:
